spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    generate-ddl: true  # 초기 개발/로컬 true 사용 주의
    hibernate:
      ddl-auto: create  # 초기 개발/로컬 create 사용 주의
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
file:
  upload:
    path: "${PWD}/work/temp/logo/"
  download:
    url: http://localhost:8080/download/
